// Realistic sample seed data for AI-Powered E-Commerce Store
// Categories: Laptops, Smartphones, Audio, Wearables, Accessories
// Curated Unsplash images of actual electronics and products

const users = [
  {
    name: 'Admin Master',
    email: 'admin@example.com',
    password: 'admin123',
    role: 'admin',
  },
  {
    name: 'Priya Sharma',
    email: 'user@example.com',
    password: 'user123',
    role: 'customer',
  },
  {
    name: 'Rahul Verma',
    email: 'rahul@example.com',
    password: 'user123',
    role: 'customer',
  },
  {
    name: 'Ananya Iyer',
    email: 'ananya@example.com',
    password: 'user123',
    role: 'customer',
  },
];

const products = [
  // LAPTOPS
  {
    name: 'Apple MacBook Air M2 (13.6-inch, 8GB RAM, 256GB SSD)',
    description: 'Strikingly thin design with the lightning-fast Apple M2 chip. Up to 18 hours of battery life, Liquid Retina display, and 1080p FaceTime HD camera. Perfect for developers, creators, and students.',
    category: 'Laptops',
    brand: 'Apple',
    price: 94900,
    discount: 8,
    images: [
      'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?auto=format&fit=crop&w=800&q=80',
    ],
    specifications: {
      Processor: 'Apple M2 8-core CPU',
      RAM: '8GB Unified Memory',
      Storage: '256GB NVMe SSD',
      Display: '13.6-inch Liquid Retina IPS (2560x1664)',
      Battery: 'Up to 18 hours 52.6Wh',
      Weight: '1.24 kg',
    },
    features: ['Silent fanless design', 'MagSafe 3 charging', 'Backlit Magic Keyboard with Touch ID', '1080p FaceTime HD camera', 'Force Touch trackpad'],
    stock: 24,
    rating: 4.8,
    numReviews: 14,
  },
  {
    name: 'ASUS TUF Gaming F15 (Intel Core i5-11400H, RTX 2050, 16GB, 512GB SSD)',
    description: 'Geared for serious gaming and high-performance coding tasks. Features a 144Hz IPS display, self-cleaning dual cooling fans, and military-grade MIL-STD-810H durability.',
    category: 'Laptops',
    brand: 'ASUS',
    price: 54990,
    discount: 15,
    images: [
      'https://images.unsplash.com/photo-1603302576837-37561b2e2302?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&w=800&q=80',
    ],
    specifications: {
      Processor: 'Intel Core i5-11400H (6 cores, up to 4.5 GHz)',
      RAM: '16GB DDR4 3200MHz',
      Storage: '512GB PCIe 3.0 NVMe SSD',
      Graphics: 'NVIDIA GeForce RTX 2050 4GB GDDR6',
      Display: '15.6-inch FHD (1920x1080) 144Hz vIPS',
      Battery: '48Wh 3-cell Li-ion',
      Weight: '2.30 kg',
    },
    features: ['144Hz high refresh rate screen', 'RGB backlit gaming keyboard', 'Dual fans with anti-dust tunnels', 'Wi-Fi 6 connectivity', 'MIL-STD-810H tested'],
    stock: 18,
    rating: 4.5,
    numReviews: 22,
  },
  {
    name: 'Lenovo IdeaPad Slim 3 (AMD Ryzen 5 5500U, 16GB RAM, 512GB SSD)',
    description: 'Sleek, lightweight productivity notebook with an ultra-thin bezel, rapid charge technology, and privacy webcam shutter. Tailored for office workflow, programming, and everyday multitasking.',
    category: 'Laptops',
    brand: 'Lenovo',
    price: 43990,
    discount: 12,
    images: [
      'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=800&q=80',
    ],
    specifications: {
      Processor: 'AMD Ryzen 5 5500U (6 cores / 12 threads)',
      RAM: '16GB DDR4 3200MHz',
      Storage: '512GB NVMe M.2 SSD',
      Display: '15.6-inch FHD Antiglare (1920x1080) 250 nits',
      Battery: 'Up to 9 hours with Rapid Charge Boost',
      Weight: '1.65 kg',
    },
    features: ['Webcam privacy shutter', 'Dolby Audio stereo speakers', 'Rapid Charge (80% in 1 hr)', 'Sleek Arctic Grey finish', 'Fingertip biometric reader'],
    stock: 35,
    rating: 4.3,
    numReviews: 19,
  },
  {
    name: 'Dell XPS 15 9530 (13th Gen Intel Core i7, 32GB RAM, 1TB SSD, RTX 4060)',
    description: 'The pinnacle of Windows laptops. InfinityEdge OLED display with 100% DCI-P3 color gamut, CNC machined aluminum chassis, and quad-speaker studio audio.',
    category: 'Laptops',
    brand: 'Dell',
    price: 219900,
    discount: 5,
    images: [
      'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?auto=format&fit=crop&w=800&q=80',
    ],
    specifications: {
      Processor: 'Intel Core i7-13700H (14 cores, up to 5.0 GHz)',
      RAM: '32GB DDR5 4800MHz',
      Storage: '1TB PCIe Gen 4 SSD',
      Graphics: 'NVIDIA GeForce RTX 4060 8GB GDDR6',
      Display: '15.6-inch 3.5K OLED Touch (3456x2160)',
      Battery: '86Wh built-in',
      Weight: '1.92 kg',
    },
    features: ['Edge-to-edge 3.5K OLED touchscreen', 'Waves Nx 3D audio quad speakers', 'Aerospace-inspired carbon fiber palm rest', 'Corning Gorilla Glass 6'],
    stock: 8,
    rating: 4.9,
    numReviews: 9,
  },

  // SMARTPHONES
  {
    name: 'Apple iPhone 15 (128GB, Blue)',
    description: 'Dynamic Island bubbles up alerts and Live Activities. 48MP main camera captures super-high-resolution photos with 2x Telephoto. Color-infused glass and aluminum design with USB-C.',
    category: 'Smartphones',
    brand: 'Apple',
    price: 71900,
    discount: 10,
    images: [
      'https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?auto=format&fit=crop&w=800&q=80',
    ],
    specifications: {
      Processor: 'A16 Bionic chip with 5-core GPU',
      Display: '6.1-inch Super Retina XDR OLED (2556x1179)',
      Camera: '48MP Main + 12MP Ultra Wide with 2x optical zoom',
      Storage: '128GB NVMe',
      Battery: 'All-day battery life (Up to 20 hours video)',
      Connectivity: '5G, Wi-Fi 6, USB-C, Bluetooth 5.3',
    },
    features: ['Dynamic Island interactive notifications', '48MP camera with next-gen portraits', 'Roadside Assistance via satellite', 'Ceramic Shield front glass', 'Water and dust resistance (IP68)'],
    stock: 40,
    rating: 4.7,
    numReviews: 31,
  },
  {
    name: 'Samsung Galaxy S24 5G (8GB RAM, 256GB, Onyx Black)',
    description: 'Galaxy AI is here. Search effortlessly with Circle to Search, get real-time voice translation on calls, and edit photos with Generative Edit. Armor Aluminum frame and Gorilla Glass Victus 2.',
    category: 'Smartphones',
    brand: 'Samsung',
    price: 79999,
    discount: 6,
    images: [
      'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&w=800&q=80',
    ],
    specifications: {
      Processor: 'Exynos 2400 Deca-Core 4nm',
      Display: '6.2-inch Dynamic AMOLED 2X, 120Hz (2600 nits)',
      Camera: '50MP Wide + 12MP Ultra-Wide + 10MP Telephoto (3x)',
      RAM: '8GB LPDDR5X',
      Battery: '4000mAh with 25W fast charging',
      OS: 'Android 14 with One UI 6.1 (7 years OS updates)',
    },
    features: ['Circle to Search with Google', 'Live Call Translation in 13 languages', 'ProVisual Engine with AI Nightography', 'Gorilla Glass Victus 2', 'IP68 water protection'],
    stock: 28,
    rating: 4.6,
    numReviews: 18,
  },
  {
    name: 'OnePlus 12R (16GB RAM, 256GB, Cool Blue)',
    description: 'Flagship killer with Qualcomm Snapdragon 8 Gen 2, fourth-gen LTPO 120Hz ProXDR display, and an enormous 5500mAh battery paired with 100W SUPERVOOC hyper charging.',
    category: 'Smartphones',
    brand: 'OnePlus',
    price: 45999,
    discount: 5,
    images: [
      'https://images.unsplash.com/photo-1580910051074-3eb694886505?auto=format&fit=crop&w=800&q=80',
    ],
    specifications: {
      Processor: 'Snapdragon 8 Gen 2 Mobile Platform',
      RAM: '16GB LPDDR5X with RAM-Vita',
      Storage: '256GB UFS 3.1',
      Display: '6.78-inch 1.5K LTPO4 AMOLED 120Hz',
      Battery: '5500mAh Dual-Cell with 100W charging',
      Camera: '50MP Sony IMX890 with OIS',
    },
    features: ['100W SUPERVOOC (1-100% in 26 mins)', 'Cryo-Velocity VC Dual Cooling chamber', 'Aqua Touch screen works in rain', 'Stereo Dolby Atmos speakers'],
    stock: 30,
    rating: 4.5,
    numReviews: 27,
  },
  {
    name: 'Google Pixel 8 (8GB RAM, 128GB, Hazel)',
    description: 'Engineered by Google with Google Tensor G3. Best-in-class computational photography with Best Take, Audio Magic Eraser, and Macro Focus.',
    category: 'Smartphones',
    brand: 'Google',
    price: 64999,
    discount: 14,
    images: [
      'https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=800&q=80',
    ],
    specifications: {
      Processor: 'Google Tensor G3 with Titan M2 security',
      RAM: '8GB LPDDR5X',
      Storage: '128GB UFS 3.1',
      Display: '6.2-inch Actua display 120Hz OLED',
      Camera: '50MP Octa PD + 12MP Ultrawide with Macro',
      Battery: '4575mAh with fast wireless Qi charging',
    },
    features: ['Audio Magic Eraser removes background noise', 'Best Take combines family photos', 'Clear Calling noise reduction', '7 years of OS and security drops'],
    stock: 20,
    rating: 4.4,
    numReviews: 15,
  },

  // AUDIO & HEADPHONES
  {
    name: 'Sony WH-1000XM5 Wireless Noise Cancelling Headphones',
    description: 'Industry-leading noise cancellation powered by two processors and eight microphones. Magnificent sound quality with 30mm driver unit and crystal clear hands-free calls.',
    category: 'Audio',
    brand: 'Sony',
    price: 29990,
    discount: 16,
    images: [
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=800&q=80',
    ],
    specifications: {
      Type: 'Over-Ear Wireless Bluetooth',
      NoiseCancellation: 'Dual Processor V1 + HD Noise Cancelling QN1',
      BatteryLife: 'Up to 30 hours with ANC on (40h off)',
      Charging: 'USB-C (3 min charge gives 3 hours playback)',
      Drivers: '30mm precision engineered carbon fiber',
      Weight: '250 grams',
    },
    features: ['Industry leading Active Noise Cancellation', 'Multipoint connection between 2 devices', 'Speak-to-Chat auto pause', 'LDAC High-Resolution Wireless Audio', 'Ultra-comfortable soft-fit leather'],
    stock: 22,
    rating: 4.8,
    numReviews: 36,
  },
  {
    name: 'boAt Rockerz 450 Bluetooth On Ear Headphones with Mic',
    description: 'Budget-friendly on-ear wireless headphones with 40mm dynamic drivers, padded ear cushions, and up to 15 hours of continuous wireless playback.',
    category: 'Audio',
    brand: 'boAt',
    price: 1499,
    discount: 62,
    images: [
      'https://images.unsplash.com/photo-1583394838336-acd977736f90?auto=format&fit=crop&w=800&q=80',
    ],
    specifications: {
      Type: 'On-Ear Wireless',
      BatteryLife: 'Up to 15 Hours',
      DriverSize: '40mm Dynamic Drivers',
      Bluetooth: 'v5.0 with 10m range',
      Weight: '168 grams',
    },
    features: ['Adaptive earcups with plush foam', 'Dual modes: Bluetooth & 3.5mm AUX', 'Integrated physical controls', 'Instant voice assistant activation'],
    stock: 80,
    rating: 4.1,
    numReviews: 45,
  },
  {
    name: 'Apple AirPods Pro (2nd Generation with USB-C)',
    description: 'Up to 2x more Active Noise Cancellation. Transparency mode lets you hear the world around you. All-new Adaptive Audio tailors noise control to your environment.',
    category: 'Audio',
    brand: 'Apple',
    price: 24900,
    discount: 4,
    images: [
      'https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?auto=format&fit=crop&w=800&q=80',
    ],
    specifications: {
      Chip: 'Apple H2 headphone chip + U1/U2 case chip',
      Audio: 'Custom high-excursion driver & amplifier',
      Battery: 'Up to 6 hours listening (30 hours with case)',
      Case: 'MagSafe Case with USB-C, speaker, and lanyard loop',
      Resistance: 'IP54 dust, sweat, and water resistant',
    },
    features: ['Next-gen Active Noise Cancellation', 'Personalized Spatial Audio with dynamic head tracking', 'Touch control for volume swipe', 'Precision Finding with Find My'],
    stock: 25,
    rating: 4.9,
    numReviews: 40,
  },
  {
    name: 'JBL Tune 760NC Wireless Over-Ear Active Noise Cancelling Headphones',
    description: 'Your music, noise free. The JBL Tune 760NC delivers punchy Pure Bass sound, active noise cancelling, and 35 hours of battery life with ANC on.',
    category: 'Audio',
    brand: 'JBL',
    price: 5999,
    discount: 25,
    images: [
      'https://images.unsplash.com/photo-1484704849700-f032a568e944?auto=format&fit=crop&w=800&q=80',
    ],
    specifications: {
      Type: 'Over-Ear Wireless',
      NoiseCancellation: 'Active Noise Cancellation (ANC)',
      BatteryLife: '35 Hours with ANC / 50 Hours with ANC off',
      FastCharging: '2 hours playback on 5 min quick charge',
      Bluetooth: 'Bluetooth 5.0 with Multipoint support',
      Weight: '220 grams',
    },
    features: ['JBL Pure Bass acoustic tuning', 'Active Noise Cancellation', 'Multi-point Bluetooth pairing', 'Hands-free calls with Voice Assistant button', 'Foldable travel-friendly hinge'],
    stock: 35,
    rating: 4.4,
    numReviews: 24,
  },

  // WEARABLES
  {
    name: 'Apple Watch Series 9 GPS 45mm (Midnight Aluminum Case)',
    description: 'Smarter, brighter, and mightier. Powered by the S9 SiP with a magical new double-tap gesture to interact without touching the screen.',
    category: 'Wearables',
    brand: 'Apple',
    price: 44900,
    discount: 6,
    images: [
      'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&w=800&q=80',
    ],
    specifications: {
      CaseSize: '45mm (Fits 140–220mm wrists)',
      Display: 'Always-On Retina LTPO OLED up to 2000 nits',
      Processor: 'S9 SiP 64-bit dual core',
      Sensors: 'ECG, Blood Oxygen, Temperature sensing, Heart Rate',
      Battery: '18 hours normal / 36 hours Low Power Mode',
      WaterResistance: '50m swimproof (WR50)',
    },
    features: ['Double tap gesture control', 'Precision Finding for iPhone', 'On-device Siri processing', 'ECG app & irregular rhythm notification', 'Crash Detection & Fall Detection'],
    stock: 20,
    rating: 4.7,
    numReviews: 17,
  },
  {
    name: 'Samsung Galaxy Watch 6 Bluetooth 44mm (Graphite)',
    description: 'Start your everyday wellness journey. Advanced sleep coaching, personalized heart rate zones, and body composition analysis packed into a sleek sapphire crystal dial.',
    category: 'Wearables',
    brand: 'Samsung',
    price: 28999,
    discount: 15,
    images: [
      'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&w=800&q=80',
    ],
    specifications: {
      Display: '1.5-inch Super AMOLED (480x480) Sapphire Crystal',
      Processor: 'Exynos W930 Dual Core 1.4GHz',
      RAM: '2GB + 16GB internal storage',
      Sensors: 'BioActive Sensor (Optical Heart + ECG + BIA)',
      Battery: '425mAh up to 40 hours',
      Durability: '5ATM + IP68 / MIL-STD-810H',
    },
    features: ['Detailed Sleep Coaching with sleep animal symbols', 'BIA Body Composition (fat %, skeletal muscle)', 'Personalized HR Zones for workouts', 'One-click interchangeable band mechanism'],
    stock: 22,
    rating: 4.5,
    numReviews: 19,
  },

  // ACCESSORIES
  {
    name: 'Logitech MX Master 3S Wireless Performance Mouse',
    description: 'An icon remastered with quiet clicks and an 8,000 DPI track-on-glass sensor. MagSpeed electromagnetic scrolling delivers precision and zero noise.',
    category: 'Accessories',
    brand: 'Logitech',
    price: 9995,
    discount: 10,
    images: [
      'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&w=800&q=80',
    ],
    specifications: {
      Sensor: 'Darkfield high precision 8000 DPI (glass tracking)',
      Buttons: '7 customizable buttons + thumb scroll wheel',
      Battery: '500mAh rechargeable (70 days on full charge)',
      Connectivity: 'Bluetooth Low Energy + Logi Bolt USB Receiver',
      Weight: '141 grams',
    },
    features: ['MagSpeed electromagnetic scrolling (1,000 lines/sec)', 'Quiet clicks with 90% less noise', 'Cross-computer Flow control between Mac & Windows', 'Ergonomic palm and thumb rest'],
    stock: 45,
    rating: 4.9,
    numReviews: 29,
  },
  {
    name: 'Keychron K2 V2 Wireless Mechanical Keyboard (RGB Backlit, Brown Switch)',
    description: 'Compact 75% layout mechanical keyboard with Gateron G Pro switches. Connects with up to 3 devices via Bluetooth 5.1 and switches easily between Mac and Windows.',
    category: 'Accessories',
    brand: 'Keychron',
    price: 8999,
    discount: 11,
    images: [
      'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=800&q=80',
    ],
    specifications: {
      Layout: '75% (84 keys)',
      Switches: 'Gateron G Pro Mechanical Brown switches',
      Backlight: '18 types of RGB backlight modes',
      Battery: '4000mAh lithium-polymer (up to 240 hours)',
      Connectivity: 'Bluetooth 5.1 & Type-C wired mode',
    },
    features: ['Mac and Windows layout keycaps included', 'Connects to 3 devices simultaneously', 'Inclined bottom frame with 2-level feet', 'Satisfying tactile mechanical typing feel'],
    stock: 18,
    rating: 4.8,
    numReviews: 21,
  },
];

const sampleReviews = [
  {
    rating: 5,
    comment: 'The M2 chip is ridiculously fast! Battery easily lasts two full working days of web development and video calls. Worth every single rupee.',
    sentiment: 'positive',
  },
  {
    rating: 5,
    comment: 'Best laptop for programming under 60k! Running VS Code and Docker containers seamlessly. Build quality is solid.',
    sentiment: 'positive',
  },
  {
    rating: 4,
    comment: 'Solid performance for the price. Keyboard feels decent and the display is clear, although battery is average.',
    sentiment: 'positive',
  },
  {
    rating: 2,
    comment: 'Gets warm during intensive tasks and battery drains faster than advertised. A bit disappointed with the speakers.',
    sentiment: 'negative',
  },
  {
    rating: 5,
    comment: 'Industry leading noise cancellation! Used it on a 4-hour flight and could not hear any engine noise. Sound signature is rich and detailed.',
    sentiment: 'positive',
  },
  {
    rating: 3,
    comment: 'Decent headphones for daily calls. Sound is okay for normal listening, but bass is somewhat overwhelming.',
    sentiment: 'neutral',
  },
];

module.exports = {
  users,
  products,
  sampleReviews,
};
